# Generated by Django 4.2.4 on 2023-08-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mafacture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='facture_type',
            new_name='type_facture',
        ),
    ]
