# Generated by Django 4.2.4 on 2023-08-15 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mafacture', '0003_alter_facture_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mafacture.client'),
        ),
    ]
